=== UoEMainLibrary/pizan/html/dtd/halfway.dtd
<!ENTITY nbsp "&#160;">

<!ELEMENT a  ( #PCDATA )>
<!ATTLIST a
href CDATA #REQUIRED
>

<!ELEMENT abbr  EMPTY>
<!ATTLIST abbr
type CDATA #REQUIRED
>


<!ELEMENT add  ( #PCDATA | abbr | c | choice  | corr | emph | fw | g | hi | l | lb | name | note | num | rhyme | s | sic | title | vs)*>
<!ATTLIST add
place CDATA #REQUIRED
evidence CDATA #REQUIRED
reason CDATA #IMPLIED
type CDATA #IMPLIED
>

<!ELEMENT author  ( #PCDATA )>

<!ELEMENT authority  ( #PCDATA )>

<!ELEMENT availability  ( p )>
<!ATTLIST availability
status CDATA #REQUIRED
>

<!ELEMENT biblFull  ( titleStmt | publicationStmt )*>

<!ELEMENT body  ( p )>
<!ATTLIST background>
<!-- the element <c> changes a lower case letter to upper-case and vice versa -->
<!ELEMENT c  ( #PCDATA | s | vs )*>

<!ELEMENT cb  EMPTY>
<!ATTLIST cb
n CDATA #REQUIRED
ed CDATA #IMPLIED
l CDATA #IMPLIED>

<!--  <choice> is the parent element of the elements <corr> and <sic> -->
<!ELEMENT choice  ( abbr | add | c | corr | emph | hi | del | lb | orig | reg | rhyme | sic )*>
<!ELEMENT corr  ( #PCDATA | c | g | hi | name | rhyme | title )*>
<!ATTLIST corr
reason CDATA #REQUIRED
rend CDATA #IMPLIED
resp CDATA #REQUIRED
source CDATA #IMPLIED
>

<!ELEMENT date  ( #PCDATA )>

<!-- Used to to mark deletions made during the preparation of the manuscript, i.e. shortly before 1414 -->
<!ELEMENT del  ( #PCDATA  | abbr | add | c | div2 | emph | fw | group | hi | lb | name | note | rhyme | s | title | vs )*>
<!ATTLIST del
evidence CDATA #IMPLIED
rend CDATA #REQUIRED
reason CDATA #IMPLIED
type CDATA #IMPLIED
>

<!-- Used to delimit each of the fascicules in the manuscript -->
<!ELEMENT div0 ( #PCDATA  | abbr |  add | c | cb | choice | corr | del | div1 | div2 | div3| div4 | div9 | emph| figure | foreign | fw | g | gb | group | hi | layout | l | lb | lg | msDesc | name | note | num | orig | p | pb | pre | ref | reg | rhyme |  s | subst | supplied | title | vs )*>
<!ATTLIST div0
n CDATA #REQUIRED
type CDATA #REQUIRED
>

<!-- Used to delimit each of the items (i.e. texts/works by Christine) in the manuscript -->
<!ELEMENT div1 ( #PCDATA  | abbr |  add | c | cb | choice | corr | del | div0 | div2 | div3| div4 | div9 | emph| figure | foreign | fw | g | gb | group | hi | layout | l | lb | lg | msDesc | name | note | num | orig | p | pb | pre | ref | reg | rhyme |  s | subst | supplied | title | vs )*>
<!ATTLIST div1
n CDATA #REQUIRED
type CDATA #REQUIRED
>

<!-- Used to number each of the items in a collection, e.g. of lyrics -->
<!ELEMENT div2  ( #PCDATA |  abbr | add | c | cb | choice | corr | del | div2 | emph | figure | foreign | fw | g | gb | group | hi | layout | l | lb | lg | name | note | num | orig | reg | pb |  rhyme |  s | subst | supplied | title | vs )*>
<!ATTLIST div2
type CDATA #IMPLIED
metre CDATA #IMPLIED
length CDATA #IMPLIED
n CDATA #REQUIRED
satfno CDATA #IMPLIED
stanza CDATA #IMPLIED
envoi CDATA #IMPLIED
rhyme CDATA #IMPLIED
refrain CDATA #IMPLIED
>

<!-- Used to tag individual 'intermÃ¨des lyriques' -->
<!ELEMENT div3  ( #PCDATA |  abbr | add | c | cb | choice | corr | del | div2 | emph | figure | foreign | fw | g | gb |glyph | hi | layout | l | lb | lg | name | note | num | pb |  rhyme |  s |  
subst | supplied | title | vs )*>
<!ATTLIST div3
type CDATA #IMPLIED
metre CDATA #IMPLIED
length CDATA #IMPLIED
n CDATA  #IMPLIED
stanza CDATA #IMPLIED
envoi CDATA #IMPLIED
rhyme CDATA #IMPLIED
refrain CDATA #IMPLIED
>

<!-- Used to delimit paragraphs in Front Matter -->
<!ELEMENT div4  ( #PCDATA  | a | emph | title  )*>

<!-- Used to group the paragraphs in Front Matter  for CSS purposes -->
<!ELEMENT div9 ( #PCDATA  | div4 | emph | title )*>

<!-- A formatting element used to mark a portion of text to be rendered in italic in HTML-->
<!ELEMENT emph  ( #PCDATA | abbr | add | c | choice | corr | del | emph | fw | g | hi | l | lb | name | note | rhyme | s | sic | subst | supplied | title  | vs )*>
<!ATTLIST emph
rend CDATA #REQUIRED
>

<!-- Used to give details of a miniature in the manuscript, where it occurs, and how many ruled lines it occupies -->
<!ELEMENT figure  EMPTY>
<!ATTLIST figure
place CDATA #REQUIRED
ref CDATA #REQUIRED
>

<!ELEMENT fileDesc  ( titleStmt | publicationStmt | sourceDesc )*>

<!-- Used to mark words in a language other than French, mainly Latin but also a very few English words,  -->
<!ELEMENT foreign ( #PCDATA | abbr | add | c | cb | choice| corr | del | div1 | div2 | div3 | emph | figure | foreign| fw | g | gb | glyph |group | hi | layout | l | lb | lg | name | note | num | orig | reg | pb | rhyme | s | sic |subst | supplied | title | vs)*>
<!ATTLIST foreign
xml:lang CDATA #REQUIRED
rend CDATA #IMPLIED
>

<!ELEMENT fw  ( #PCDATA | hi | s | abbr | add | del | c | choice | emph | foreign | g | glyph | l |rhyme | name | note | lb | num | orig | reg | subst | supplied | title | vs )*>
<!ATTLIST fw
type CDATA #IMPLIED
place CDATA #IMPLIED
rend CDATA #IMPLIED
size CDATA #IMPLIED
>

<!-- A 'temporary' element used to list lemmas and build a glossary with meanings in English and French -->
<!ELEMENT g  ( #PCDATA | abbr | add | c | choice| corr | del | emph | fw | l | lb |  name | note | rhyme | s | sic | subst | supplied | title | vs )*>
<!ATTLIST g
lemma CDATA #REQUIRED
en CDATA #REQUIRED
fr CDATA #REQUIRED
type CDATA #IMPLIED
>

<!-- 'Gathering begins', used to mark where a gathering (quire) begins; 'n' numbers the quires in sequence; 'rend' indicates the number of leaves in the quire. -->
<!ELEMENT gb  EMPTY>
<!ATTLIST gb
n CDATA #REQUIRED
rend CDATA #REQUIRED
type CDATA #IMPLIED
>

<!ELEMENT glyph ( #PCDATA | abbr | add | c | cb | corr | choice | del | fw | g | glyph | hi | layout | l | lb | name | note | num | orig | pb | reg | s | sic | subst | supplied | vs )*>

<!ATTLIST glyph
type CDATA #REQUIRED
>

<!ELEMENT group  EMPTY>
<!ATTLIST group
n CDATA #REQUIRED
>

<!-- <hi> = 'high rendition' marks the way(s) in which a letter, word or short passage of text has been highlighted during the preparation of the manuscript -->
<!ELEMENT hi  ( #PCDATA | abbr | add | c | cb | corr | choice | del | fw | g | glyph | hi | foreign | layout | l | lb | name | note | num | orig | pb | reg | s | sic | subst | supplied | vs )*>
<!ATTLIST hi
rend CDATA #REQUIRED
type CDATA #IMPLIED
>

<!ELEMENT idno  ( #PCDATA )>
<!ATTLIST idno
type CDATA #REQUIRED
>

<!-- Line number -->
<!ELEMENT l  EMPTY>
<!ATTLIST l
n CDATA #REQUIRED
>

<!-- <layout> indicates how many ruled lines are contained in a column of the manuscript -->
<!ELEMENT layout  EMPTY>
<!ATTLIST layout
ruledLines CDATA #REQUIRED
rend CDATA #IMPLIED
writtenLines CDATA #IMPLIED
>

<!-- Used to mark a page break -->
<!ELEMENT lb  EMPTY>
<!ATTLIST lb
n CDATA #REQUIRED
>

<!--  a group of lines or a stanza. The element is reserved for future use, <div2> being used for this purpose for the moment -->
<!ELEMENT lg  ( #PCDATA | hi | g | lb | rhyme | name | l | choice | note | cb | layout | del | pb | s | c | abbr | add | vs )*>
<!ATTLIST lg
n CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT msDesc  ( div0 | div1 | div2 | div3 | div4 )*>

<!-- Used to mark proper names: names of people or places; personifications etc  -->
<!ELEMENT name  ( #PCDATA | abbr | add | c | cb | choice | corr | del | emph | foreign | fw | g | hi | l | layout | lb | name | note | num  | rhyme | s | sic | subst | title | vs )*>
<!ATTLIST name
ref CDATA #IMPLIED
>

<!ELEMENT note  ( #PCDATA  | abbr | add | emph | hi | name | title )*>

<!ELEMENT num ( #PCDATA | fw | choice | lb | abbr | note | s | name | vs )*>
<!ATTLIST num
type CDATA #REQUIRED
>

<!-- the element <orig> is used in conjunction with <reg> to change '&' to 'et'   -->
<!ELEMENT orig  ( #PCDATA )>

<!ELEMENT p  ( #PCDATA | div0 | div1 | emph | gb | ref | title)*>

<!-- Used to mark a page break -->
<!ELEMENT pb  EMPTY>
<!ATTLIST pb
n CDATA #REQUIRED
ed CDATA #REQUIRED
l CDATA #IMPLIED
>
<!ELEMENT pre  ( #PCDATA | div4 )*>

<!ELEMENT publicationStmt  ( authority | availability | date | publisher | pubPlace | idno )*>

<!ELEMENT publisher  ( #PCDATA )>

<!ELEMENT pubPlace  ( #PCDATA )>

<!ELEMENT ref  ( #PCDATA )>
<!ATTLIST ref
type CDATA #REQUIRED
>

<!-- see <orig> -->
<!ELEMENT reg  ( #PCDATA | s )*>

<!ELEMENT resp  ( #PCDATA )>

<!ELEMENT respStmt  ( resp | name )*>

<!ELEMENT rhyme  ( #PCDATA | c | abbr | choice | corr | foreign | g | s | lb | num | sic | subst | add | note |  name | del | title | vs )*>

<!-- <s> 'special', used to mark an exuberant, elaborate or unusually formed letter which is extended, generally into the upper or lower margin. Values of 'rend' include 'arabesque', 'banderole', 'commas', 'flattened', 'point' and 'trumpet'. -->
<!ELEMENT s  ( #PCDATA | c | abbr | reg )*>
<!ATTLIST s
rend CDATA #IMPLIED
>

<!ELEMENT sourceDesc  ( biblFull )>

<!-- Used to mark a portion of the text in Harley 4431 which the modern transcriber/editoris considers to be incorrect -->
<!ELEMENT sic  ( #PCDATA | abbr | add | c | del | fw | hi | lb | name | s  | vs)*>



<!ELEMENT subst  ( #PCDATA | abbr | del | add )*>

<!ELEMENT supplied ( #PCDATA | c | del | fw | group | hi | lb | name | note | title )*>
<!ATTLIST supplied
reason CDATA #REQUIRED
rend CDATA #IMPLIED
resp CDATA #REQUIRED
source CDATA #IMPLIED
>

<!ELEMENT TEI  ( teiHeader | text )*>

<!ELEMENT teiHeader  ( fileDesc )>

<!ELEMENT text  ( body )>

<!ELEMENT title   ( #PCDATA | abbr | add | c | cb | choice | corr | del | emph | fw | g | hi | l | layout | lb | name | note | num  | rhyme | s | sic | subst | vs  )*>
<!ATTLIST title
type CDATA #IMPLIED
>

<!ELEMENT titleStmt  ( title | author | respStmt )*>

<!-- <vs>, 'very special', used to mark a particularly exuberant, elaborate or unusually formed letter which is extended, generally into the upper or lower) margin. Values of 'rend' include 'arabesque', 'banderole', 'commas', 'flattened', 'point' and 'trumpet'. -->
<!ELEMENT vs  ( #PCDATA | c | abbr )*>
<!ATTLIST vs
rend CDATA #IMPLIED
>

=== UoEMainLibrary/pizan/html/xmlfinal/topandtail.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--?DOCTYPE TEI SYSTEM "http://projects.oucs.ox.ac.uk/ENRICH/ODD/RomaResults/enrich.dtd" -->
<!DOCTYPE TEI SYSTEM "halfway.dtd">
<?xml-stylesheet type="text/xsl" href="student.xsl"?>
<?xml-stylesheet type="text/css" href="classes.css"?>
<TEI>
<teiHeader>
<fileDesc>
<titleStmt>
<title>London, British Library, Harley MS 4431</title>
<author>Christine de Pizan</author>
<respStmt>
<resp>Marked up by</resp><name>Team funded under AHRC 
award</name>
</respStmt></titleStmt>
<publicationStmt>
<authority>AHRC funded research project in Middle French 2004 to 2009 
contact James.Laidlaw
at ed.ac.uk</authority>
<availability 
status="free"><p>http://www.pizan.lib.ed.ac.uk/</p></availability>
<date>2008</date>
</publicationStmt>
<sourceDesc>
<biblFull>
<titleStmt>
<title>The Queen's Manuscript</title>
<author>Christine de Pizan</author>
</titleStmt>
<publicationStmt>
<publisher>Manuscript</publisher>
<pubPlace>Paris</pubPlace>
<date>1414</date>
<idno 
type="url">http://www.bl.uk/catalogues/illuminatedmanuscripts</idno>
</publicationStmt></biblFull>
</sourceDesc></fileDesc>
</teiHeader>
<text>
<body>
<p>



</p>
</body>
</text>
</TEI>

=== UoEMainLibrary/pizan/html/xmlfinal/cebafm.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--?DOCTYPE TEI SYSTEM "http://www.tei-c.org/release/xml/tei/custom/schema/dtd/tei_all.dtd" -->
<!DOCTYPE TEI SYSTEM "halfway.dtd">
<?xml-stylesheet href="fiche.xsl" type="text/xsl"?>
<TEI>
<teiHeader>
<fileDesc>
<titleStmt>
<title>London, British Library, Harley MS 4431</title>
<author>Christine de Pizan</author>
<respStmt>
<resp>Marked up by</resp><name>Team funded under AHRC award</name>
</respStmt></titleStmt>
<publicationStmt>
<authority>AHRC funded research project (2004-2009) centred on London, British Library, Harley MS 4431, the collection of her works prepared by Christine de Pizan and presented by her to Queen Isabeau of France early in 1414.  Contact Charlie.Mansfield@ ed.ac.uk</authority>
<availability status="free"><p>http://www.pizan.lib.ed.ac.uk/</p></availability>
<date>2008</date>
</publicationStmt>
<sourceDesc>
<biblFull>
<titleStmt>
<title>The Queen's Manuscript</title>
<author>Christine de Pizan</author>
</titleStmt>
<publicationStmt>
<publisher>Manuscript</publisher>
<pubPlace>Paris</pubPlace>
<date>1414</date>
<idno type="url">http://www.bl.uk/catalogues/illuminatedmanuscripts</idno>
</publicationStmt></biblFull>
</sourceDesc></fileDesc>
</teiHeader>
<text>
<body>
<p>
<div1 n="1" type="1">

<div9>
<div4><title type="main"><emph rend="headline">Cent Balades</emph></title></div4>
<div4>The ruling of ff. 4-11 makes no provision for running titles.</div4>

</div9>

</div1>
</p>
</body>
</text>
</TEI>

=== UoEMainLibrary/pizan/html/xmlfinal/prel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--?DOCTYPE TEI SYSTEM "http://www.tei-c.org/release/xml/tei/custom/schema/dtd/tei_all.dtd" -->
<!DOCTYPE TEI SYSTEM "halfway.dtd">
<?xml-stylesheet href="student.xsl" type="text/xsl"?>
<?xml-stylesheet type="text/css" href="classes.css"?>
<TEI>
<teiHeader>
<fileDesc>
<titleStmt>
<title>London, British Library, Harley MS 4431</title>
<author>Christine de Pizan</author>
<respStmt>
<resp>Marked up by</resp><name>Team funded under AHRC award</name>
</respStmt></titleStmt>
<publicationStmt>
<authority>AHRC funded research project in Middle French 2004 to 2009 contact Charlie.Mansfield
at ed.ac.uk</authority>
<availability status="free"><p>http://www.pizan.lib.ed.ac.uk/</p></availability>
<date>2008</date>
</publicationStmt>
<sourceDesc>
<biblFull>
<titleStmt>
<title>The Queen's Manuscript</title>
<author>Christine de Pizan</author>
</titleStmt>
<publicationStmt>
<publisher>Manuscript</publisher>
<pubPlace>Paris</pubPlace>
<date>1414</date>
<idno type="url">http://www.bl.uk/catalogues/illuminatedmanuscripts</idno>
</publicationStmt></biblFull>
</sourceDesc></fileDesc>
</teiHeader>
<text>
<body>
<p>
<div1 n="Preliminary Leaves" type="Item">
<pb n="001" ed="r"/>
<lb n="PREL.001r:01"/><note>The page is unruled; it contains three devices, all associated with names and in different hands, and one ex-libris.</note>
<cb n="a"/>
<!-- 5 blank line(s) here -->
<lb n="PREL.001a:06"/>sur tous autres <note>The device of Jacquette of Luxembourg, Duchess of Bedford.</note>
<lb n="PREL.001a:07"/><name ref="Jacquette of Luxembourg, Duchesse of Bedford">Jaquete</name>
<!-- 3 blank line(s) here -->
<lb n="PREL.001a:11"/>Plus est en vous<note>The device of Louis de Bruges, seigneur de la Gruthuyse († 1492)</note> <note>Preceded and followed by a paraph.</note>
<lb n="PREL.001a:12"/><name ref="Louis de Bruges, seigneur de la Gruthuyse († 1492)"><c>g</c>ruthuse</name> <note>Preceded and followed by a paraph.</note>
<!-- 4 blank line(s) here -->
<lb n="PREL.001a:17"/><name ref="Henry Cavendish, Second Duke of Newcastle († 1691)"><foreign xml:lang="en">Duke of Newcastle</foreign></name>
<lb n="PREL.001a:18"/><foreign xml:lang="en">his booke</foreign> 1676 <note>The ex-libris is written on a rectangle of paper pasted on to the parchment, and spanning the width of the page.</note><cb n="b"/>
<!-- 5 blank line(s) here -->
<lb n="PREL.001b:06"/>M <note>A decorative 'M' is centred above the device.</note>
<lb n="PREL.001b:07"/>NULLE LA VAULT <note>The device of Anthony Woodville, Second Earl Rivers.</note>
<lb n="PREL.001b:08"/><name ref="Anthony Woodville, Second Earl Rivers ">ARIVIERES</name> <note>The names is centred below the device.</note>
<pb n="001" ed="v"/> <note>The page shows traces of ruling in plummet.</note>
<pb n="002" ed="r"/><note>The page is ruled in plummet, probably with 39 lines. A 'X' can be seen in the top right-hand corner ogf the page.</note>>
</div1>
</p>
</body>
</text>
</TEI>

=== UoEMainLibrary/pizan/html/xmlfinal/eabafm.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--?DOCTYPE TEI SYSTEM "http://www.tei-c.org/release/xml/tei/custom/schema/dtd/tei_all.dtd" -->
<!DOCTYPE TEI SYSTEM "halfway.dtd">
<?xml-stylesheet href="fiche.xsl" type="text/xsl"?>
<TEI>
<teiHeader>
<fileDesc>
<titleStmt>
<title>London, British Library, Harley MS 4431</title>
<author>Christine de Pizan</author>
<respStmt>
<resp>Marked up by</resp><name>Team funded under AHRC award</name>
</respStmt></titleStmt>
<publicationStmt>
<authority>AHRC funded research project (2004-2009) centred on London, British Library, Harley MS 4431, the collection of her works prepared by Christine de Pizan and presented by her to Queen Isabeau of France early in 1414.  Contact pizan@ed.ac.uk</authority>
<availability status="free"><p>http://www.pizan.lib.ed.ac.uk/</p></availability>
<date>2008</date>
</publicationStmt>
<sourceDesc>
<biblFull>
<titleStmt>
<title>The Queen's Manuscript</title>
<author>Christine de Pizan</author>
</titleStmt>
<publicationStmt>
<publisher>Manuscript</publisher>
<pubPlace>Paris</pubPlace>
<date>1414</date>
<idno type="url">http://www.bl.uk/catalogues/illuminatedmanuscripts</idno>
</publicationStmt></biblFull>
</sourceDesc></fileDesc>
</teiHeader>
<text>
<body>
<p>
<div1 n="1" type="1">
<div9>
<div4><title type="main"><emph rend="headline">Encore Aultres Balades</emph></title></div4>
<div4>Harley MS 4431 contains the only known copy of <emph rend="italic">Encore Aultres Balades</emph>; the name is misleading for these 9 poems consist of  4 <emph rend="italic">rondeaux quatrains</emph>, 4 <emph rend="italic">balades simples</emph> and 1 <emph rend="italic">balade layée</emph>.</div4>
<div4>Although the collection has no rubric, the four lines left blank before the first poem, together with two faint dots closeby in the outer margin, show that one was planned. The rubric supplied in this edition mirrors the only running title, at the top of fol. 049v, and echoes the title found in the Table of Contents.</div4>
 <div4>The collection was inserted into the Queen's MS at the very last moment, witness the very unusual structure of Quire 5 and the allusions in the final poem to the expedition led by the Duke of Bourbon which culminated in the capture of Soubise on 23 November 1413. For the significance of these references in dating the Queen's MS see  "<a href="http://www.pizan.lib.ed.ac.uk/harley4431date.pdf"/>.</div4>
</div9>
</div1>
</p>
</body>
</text>
</TEI>

=== UoEMainLibrary/pizan/html/xmlfinal/dvalfm.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--?DOCTYPE TEI SYSTEM "http://www.tei-c.org/release/xml/tei/custom/schema/dtd/tei_all.dtd" -->
<!DOCTYPE TEI SYSTEM "halfway.dtd">
<?xml-stylesheet href="fiche.xsl" type="text/xsl"?>
<?xml-stylesheet type="text/css" href="classes.css"?>
<TEI>
<teiHeader>
<fileDesc>
<titleStmt>
<title>London, British Library, Harley MS 4431</title>
<author>Christine de Pizan</author>
<respStmt>
<resp>Marked up by</resp><name>Team funded under AHRC award</name>
</respStmt></titleStmt>
<publicationStmt>
<authority>AHRC funded research project (2004-2009) centred on London, British Library, Harley MS 4431, the collection of her works prepared by Christine de Pizan and presented by her to Queen Isabeau of France early in 1414.  Contact Charlie.Mansfield@ ed.ac.uk</authority>
<availability status="free"><p>http://www.pizan.lib.ed.ac.uk/</p></availability>
<date>2008</date>
</publicationStmt>
<sourceDesc>
<biblFull>
<titleStmt>
<title>The Queen's Manuscript</title>
<author>Christine de Pizan</author>
</titleStmt>
<publicationStmt>
<publisher>Manuscript</publisher>
<pubPlace>Paris</pubPlace>
<date>1414</date>
<idno type="url">http://www.bl.uk/catalogues/illuminatedmanuscripts</idno>
</publicationStmt></biblFull>
</sourceDesc></fileDesc>
</teiHeader>
<text>
<body>
<p>
<div1 n="1" type="1">

<!-- New document created with EditiX at Mon Feb 16 13:53:54 GMT 2009 -->

<div9>
<div4><title type="main"><emph rend="headline">Le Livre du duc des vrais amans</emph></title>
</div4>
<div4>The <emph rend="italic">Livre du duc des vrais amans</emph> is divided into 6 sections:
</div4>
<div4>
1) the <emph rend="italic">Livre</emph> (DVAL), a narrative in heptasyllabic couplets,
    interspersed with <emph rend="italic">formes fixes</emph> (15 ballades, 3 rondeaux,
    1 virelai) and 8 letters in prose. 
</div4>
<div4>
2) an epilogue (DVAE) made up of 12 heptasyllabic couplets.

</div4>
<div4>
3) a collection of 9 <emph rend="italic">Balades de plusieurs façons</emph> (DVAB).
</div4>
<div4>
4) a collection of 3 <emph rend="italic">Virelais</emph> (DVAV).
</div4>
<div4>
5) a collection of 4 <emph rend="italic">Rondiaulx</emph> (DVAR).
</div4>
<div4>
6) a <emph rend="italic">Complainte</emph> (DVAC).
</div4>
<div4>The <emph rend="italic">Livre du duc des vrais amans</emph> 
is extant in only two manuscripts, London, BL, Harley 4431 andParis, BnF, f.fr. 836.
The work was edited by Maurice Roy in 1896 (<emph rend="italic">Oeuvres poétiques de
Christine de Pisan</emph>, Paris: SATF, vol. 3,  pp. 59-208), who based his text on the Paris MS. 
A new edition, based on the Harley MS, was published by Thelma S. Fenster in 1995:
 (<emph rend="italic">Christine de Pizan: Le Livre du duc des vrais amans</emph>, Binghamton, NY:
Medieval &amp; Renaissance texts &amp; studies 124, 261 pp.).
The verse lines are numbered in both editions. From line 2066 onwards Fenster's
line numbers, which are used here, 
are greater by one than those in Roy's edition, because
Fenster numbers the missing line, discussed below.</div4>
<div4>
The copy of the <emph rend="italic">Livre du duc des vrais amans</emph> in the
Queen's MS is carefully executed; the text is notably free of
abbreviations. The errors and emendations made by the scribe
and the reviser's corrections are surprisingly few in number.
Lines of verse have been copied twice on ff. 151c and 174b,
the second copy being scored out. The scribe has left a blank
line on fol. 157c to show that line 2067 is missing.
</div4>
<div4>The work contains five 'split rhymes': 
 The first syllable(s) of the rhyme-word provide the rhyme and the
 remaining syllable(s) are carried over to the next line.  
Two of the split rhymes are adverbs ending in <emph rend="italic">–ment</emph> (lines 1513-4, 1598-9),
 two are a form  of <emph rend="italic">avoir</emph> (lines 2055-6, 2385-6); the last example
is <emph rend="italic">tour–noyé</emph> (lines 953-4) . The scribe has copied <emph rend="italic">-Ment</emph> once with a capital;
in all the other instances the new line begins with a small letter,
which has been retained.</div4>
<div4>
The refrains of the <emph rend="italic">ballades</emph>, are written
 now in full, now in abbreviated form. The  refrains of 
<emph rend="italic">virelais</emph> <emph rend="italic">rondeaux</emph> 
are presented differently: they are always abbreviated and always inset.  Both layouts have been reproduced, as has the use - and
sometimes the absence - of blank lines. The majority of the errors
in the text have been corrected by reference to BnF, f.fr. 836.</div4>
<div4>The refrains have been set in italic, in accordance with modern practice.</div4>
</div9>
</div1>
</p>
</body>
</text>
</TEI>

=== UoEMainLibrary/pizan/html/xmlfinal/cmp2fm.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--?DOCTYPE TEI SYSTEM "http://www.tei-c.org/release/xml/tei/custom/schema/dtd/tei_all.dtd" -->
<!DOCTYPE TEI SYSTEM "halfway.dtd">
<?xml-stylesheet href="fiche.xsl" type="text/xsl"?>
<?xml-stylesheet type="text/css" href="classes.css"?>
<TEI>
<teiHeader>
<fileDesc>
<titleStmt>
<title>London, British Library, Harley MS 4431</title>
<author>Christine de Pizan</author>
<respStmt>
<resp>Marked up by</resp><name>Team funded under AHRC award</name>
</respStmt></titleStmt>
<publicationStmt>
<authority>AHRC funded research project (2004-2009) centred on London, British Library, Harley MS 4431, the collection of her works prepared by Christine de Pizan and presented by her to Queen Isabeau of France early in 1414.  Contact Charlie.Mansfield@ ed.ac.uk</authority>
<availability status="free"><p>http://www.pizan.lib.ed.ac.uk/</p></availability>
<date>2008</date>
</publicationStmt>
<sourceDesc>
<biblFull>
<titleStmt>
<title>The Queen's Manuscript</title>
<author>Christine de Pizan</author>
</titleStmt>
<publicationStmt>
<publisher>Manuscript</publisher>
<pubPlace>Paris</pubPlace>
<date>1414</date>
<idno type="url">http://www.bl.uk/catalogues/illuminatedmanuscripts</idno>
</publicationStmt></biblFull>
</sourceDesc></fileDesc>
</teiHeader>
<text>
<body>
<p>
<div1 n="1" type="1">
<div9>
<div4><title type="main"><emph rend="headline">Complainte Amoureuse</emph></title></div4>
<div4>Harley MS 4431 contains the only known copy of the <emph rend="italic">Complainte Amoureuse</emph>. The unusual structure of Quire 5 shows that the <emph rend="italic">Complainte</emph>, like <emph rend="italic">Encore Aultres Balades</emph>, the item immediately following, was added to the Queen's MS at the very last minute.</div4>
<div4>The <emph rend="italic">Complainte</emph> is introduced by a miniature and a rubric; there is only one running title, on fol. 49r. The poem is made up of 12 seizains, rhyming <emph rend="italic">a10a10a10b4b10b10b10c4c10c10c10d4d10d10d10e4e10e10e10f4</emph> etc. The opening line of each stanza is set off: by a champie initial with a border (Stanza 1) or by a paragraph mark (Stanzas 2-12); unusually, Stanza 9 contains a second paragraph mark, at line 135. A blank line has been left after each stanza, except after Stanzas 2 and 11. Lines 149-51 have been copied twice; the second version is scored through by a single vertical line.</div4>
</div9>
</div1>
</p>
</body>
</text>
</TEI>
