=== UoEMainLibrary/pizan/html/dtd/halfway.dtd
<!ENTITY nbsp "&#160;">

<!ELEMENT a  ( #PCDATA )>
<!ATTLIST a
href CDATA #REQUIRED
>

<!ELEMENT abbr  EMPTY>
<!ATTLIST abbr
type CDATA #REQUIRED
>


<!ELEMENT add  ( #PCDATA | abbr | c | choice  | corr | emph | fw | g | hi | l | lb | name | note | num | rhyme | s | sic | title | vs)*>
<!ATTLIST add
place CDATA #REQUIRED
evidence CDATA #REQUIRED
reason CDATA #IMPLIED
type CDATA #IMPLIED
>

<!ELEMENT author  ( #PCDATA )>

<!ELEMENT authority  ( #PCDATA )>

<!ELEMENT availability  ( p )>
<!ATTLIST availability
status CDATA #REQUIRED
>

<!ELEMENT biblFull  ( titleStmt | publicationStmt )*>

<!ELEMENT body  ( p )>
<!ATTLIST background>
<!-- the element <c> changes a lower case letter to upper-case and vice versa -->
<!ELEMENT c  ( #PCDATA | s | vs )*>

<!ELEMENT cb  EMPTY>
<!ATTLIST cb
n CDATA #REQUIRED
ed CDATA #IMPLIED
l CDATA #IMPLIED>

<!--  <choice> is the parent element of the elements <corr> and <sic> -->
<!ELEMENT choice  ( abbr | add | c | corr | emph | hi | del | lb | orig | reg | rhyme | sic )*>
<!ELEMENT corr  ( #PCDATA | c | g | hi | name | rhyme | title )*>
<!ATTLIST corr
reason CDATA #REQUIRED
rend CDATA #IMPLIED
resp CDATA #REQUIRED
source CDATA #IMPLIED
>

<!ELEMENT date  ( #PCDATA )>

<!-- Used to to mark deletions made during the preparation of the manuscript, i.e. shortly before 1414 -->
<!ELEMENT del  ( #PCDATA  | abbr | add | c | div2 | emph | fw | group | hi | lb | name | note | rhyme | s | title | vs )*>
<!ATTLIST del
evidence CDATA #IMPLIED
rend CDATA #REQUIRED
reason CDATA #IMPLIED
type CDATA #IMPLIED
>

<!-- Used to delimit each of the fascicules in the manuscript -->
<!ELEMENT div0 ( #PCDATA  | abbr |  add | c | cb | choice | corr | del | div1 | div2 | div3| div4 | div9 | emph| figure | foreign | fw | g | gb | group | hi | layout | l | lb | lg | msDesc | name | note | num | orig | p | pb | pre | ref | reg | rhyme |  s | subst | supplied | title | vs )*>
<!ATTLIST div0
n CDATA #REQUIRED
type CDATA #REQUIRED
>

<!-- Used to delimit each of the items (i.e. texts/works by Christine) in the manuscript -->
<!ELEMENT div1 ( #PCDATA  | abbr |  add | c | cb | choice | corr | del | div0 | div2 | div3| div4 | div9 | emph| figure | foreign | fw | g | gb | group | hi | layout | l | lb | lg | msDesc | name | note | num | orig | p | pb | pre | ref | reg | rhyme |  s | subst | supplied | title | vs )*>
<!ATTLIST div1
n CDATA #REQUIRED
type CDATA #REQUIRED
>

<!-- Used to number each of the items in a collection, e.g. of lyrics -->
<!ELEMENT div2  ( #PCDATA |  abbr | add | c | cb | choice | corr | del | div2 | emph | figure | foreign | fw | g | gb | group | hi | layout | l | lb | lg | name | note | num | orig | reg | pb |  rhyme |  s | subst | supplied | title | vs )*>
<!ATTLIST div2
type CDATA #IMPLIED
metre CDATA #IMPLIED
length CDATA #IMPLIED
n CDATA #REQUIRED
satfno CDATA #IMPLIED
stanza CDATA #IMPLIED
envoi CDATA #IMPLIED
rhyme CDATA #IMPLIED
refrain CDATA #IMPLIED
>

<!-- Used to tag individual 'intermÃ¨des lyriques' -->
<!ELEMENT div3  ( #PCDATA |  abbr | add | c | cb | choice | corr | del | div2 | emph | figure | foreign | fw | g | gb |glyph | hi | layout | l | lb | lg | name | note | num | pb |  rhyme |  s |  
subst | supplied | title | vs )*>
<!ATTLIST div3
type CDATA #IMPLIED
metre CDATA #IMPLIED
length CDATA #IMPLIED
n CDATA  #IMPLIED
stanza CDATA #IMPLIED
envoi CDATA #IMPLIED
rhyme CDATA #IMPLIED
refrain CDATA #IMPLIED
>

<!-- Used to delimit paragraphs in Front Matter -->
<!ELEMENT div4  ( #PCDATA  | a | emph | title  )*>

<!-- Used to group the paragraphs in Front Matter  for CSS purposes -->
<!ELEMENT div9 ( #PCDATA  | div4 | emph | title )*>

<!-- A formatting element used to mark a portion of text to be rendered in italic in HTML-->
<!ELEMENT emph  ( #PCDATA | abbr | add | c | choice | corr | del | emph | fw | g | hi | l | lb | name | note | rhyme | s | sic | subst | supplied | title  | vs )*>
<!ATTLIST emph
rend CDATA #REQUIRED
>

<!-- Used to give details of a miniature in the manuscript, where it occurs, and how many ruled lines it occupies -->
<!ELEMENT figure  EMPTY>
<!ATTLIST figure
place CDATA #REQUIRED
ref CDATA #REQUIRED
>

<!ELEMENT fileDesc  ( titleStmt | publicationStmt | sourceDesc )*>

<!-- Used to mark words in a language other than French, mainly Latin but also a very few English words,  -->
<!ELEMENT foreign ( #PCDATA | abbr | add | c | cb | choice| corr | del | div1 | div2 | div3 | emph | figure | foreign| fw | g | gb | glyph |group | hi | layout | l | lb | lg | name | note | num | orig | reg | pb | rhyme | s | sic |subst | supplied | title | vs)*>
<!ATTLIST foreign
xml:lang CDATA #REQUIRED
rend CDATA #IMPLIED
>

<!ELEMENT fw  ( #PCDATA | hi | s | abbr | add | del | c | choice | emph | foreign | g | glyph | l |rhyme | name | note | lb | num | orig | reg | subst | supplied | title | vs )*>
<!ATTLIST fw
type CDATA #IMPLIED
place CDATA #IMPLIED
rend CDATA #IMPLIED
size CDATA #IMPLIED
>

<!-- A 'temporary' element used to list lemmas and build a glossary with meanings in English and French -->
<!ELEMENT g  ( #PCDATA | abbr | add | c | choice| corr | del | emph | fw | l | lb |  name | note | rhyme | s | sic | subst | supplied | title | vs )*>
<!ATTLIST g
lemma CDATA #REQUIRED
en CDATA #REQUIRED
fr CDATA #REQUIRED
type CDATA #IMPLIED
>

<!-- 'Gathering begins', used to mark where a gathering (quire) begins; 'n' numbers the quires in sequence; 'rend' indicates the number of leaves in the quire. -->
<!ELEMENT gb  EMPTY>
<!ATTLIST gb
n CDATA #REQUIRED
rend CDATA #REQUIRED
type CDATA #IMPLIED
>

<!ELEMENT glyph ( #PCDATA | abbr | add | c | cb | corr | choice | del | fw | g | glyph | hi | layout | l | lb | name | note | num | orig | pb | reg | s | sic | subst | supplied | vs )*>

<!ATTLIST glyph
type CDATA #REQUIRED
>

<!ELEMENT group  EMPTY>
<!ATTLIST group
n CDATA #REQUIRED
>

<!-- <hi> = 'high rendition' marks the way(s) in which a letter, word or short passage of text has been highlighted during the preparation of the manuscript -->
<!ELEMENT hi  ( #PCDATA | abbr | add | c | cb | corr | choice | del | fw | g | glyph | hi | foreign | layout | l | lb | name | note | num | orig | pb | reg | s | sic | subst | supplied | vs )*>
<!ATTLIST hi
rend CDATA #REQUIRED
type CDATA #IMPLIED
>

<!ELEMENT idno  ( #PCDATA )>
<!ATTLIST idno
type CDATA #REQUIRED
>

<!-- Line number -->
<!ELEMENT l  EMPTY>
<!ATTLIST l
n CDATA #REQUIRED
>

<!-- <layout> indicates how many ruled lines are contained in a column of the manuscript -->
<!ELEMENT layout  EMPTY>
<!ATTLIST layout
ruledLines CDATA #REQUIRED
rend CDATA #IMPLIED
writtenLines CDATA #IMPLIED
>

<!-- Used to mark a page break -->
<!ELEMENT lb  EMPTY>
<!ATTLIST lb
n CDATA #REQUIRED
>

<!--  a group of lines or a stanza. The element is reserved for future use, <div2> being used for this purpose for the moment -->
<!ELEMENT lg  ( #PCDATA | hi | g | lb | rhyme | name | l | choice | note | cb | layout | del | pb | s | c | abbr | add | vs )*>
<!ATTLIST lg
n CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT msDesc  ( div0 | div1 | div2 | div3 | div4 )*>

<!-- Used to mark proper names: names of people or places; personifications etc  -->
<!ELEMENT name  ( #PCDATA | abbr | add | c | cb | choice | corr | del | emph | foreign | fw | g | hi | l | layout | lb | name | note | num  | rhyme | s | sic | subst | title | vs )*>
<!ATTLIST name
ref CDATA #IMPLIED
>

<!ELEMENT note  ( #PCDATA  | abbr | add | emph | hi | name | title )*>

<!ELEMENT num ( #PCDATA | fw | choice | lb | abbr | note | s | name | vs )*>
<!ATTLIST num
type CDATA #REQUIRED
>

<!-- the element <orig> is used in conjunction with <reg> to change '&' to 'et'   -->
<!ELEMENT orig  ( #PCDATA )>

<!ELEMENT p  ( #PCDATA | div0 | div1 | emph | gb | ref | title)*>

<!-- Used to mark a page break -->
<!ELEMENT pb  EMPTY>
<!ATTLIST pb
n CDATA #REQUIRED
ed CDATA #REQUIRED
l CDATA #IMPLIED
>
<!ELEMENT pre  ( #PCDATA | div4 )*>

<!ELEMENT publicationStmt  ( authority | availability | date | publisher | pubPlace | idno )*>

<!ELEMENT publisher  ( #PCDATA )>

<!ELEMENT pubPlace  ( #PCDATA )>

<!ELEMENT ref  ( #PCDATA )>
<!ATTLIST ref
type CDATA #REQUIRED
>

<!-- see <orig> -->
<!ELEMENT reg  ( #PCDATA | s )*>

<!ELEMENT resp  ( #PCDATA )>

<!ELEMENT respStmt  ( resp | name )*>

<!ELEMENT rhyme  ( #PCDATA | c | abbr | choice | corr | foreign | g | s | lb | num | sic | subst | add | note |  name | del | title | vs )*>

<!-- <s> 'special', used to mark an exuberant, elaborate or unusually formed letter which is extended, generally into the upper or lower margin. Values of 'rend' include 'arabesque', 'banderole', 'commas', 'flattened', 'point' and 'trumpet'. -->
<!ELEMENT s  ( #PCDATA | c | abbr | reg )*>
<!ATTLIST s
rend CDATA #IMPLIED
>

<!ELEMENT sourceDesc  ( biblFull )>

<!-- Used to mark a portion of the text in Harley 4431 which the modern transcriber/editoris considers to be incorrect -->
<!ELEMENT sic  ( #PCDATA | abbr | add | c | del | fw | hi | lb | name | s  | vs)*>



<!ELEMENT subst  ( #PCDATA | abbr | del | add )*>

<!ELEMENT supplied ( #PCDATA | c | del | fw | group | hi | lb | name | note | title )*>
<!ATTLIST supplied
reason CDATA #REQUIRED
rend CDATA #IMPLIED
resp CDATA #REQUIRED
source CDATA #IMPLIED
>

<!ELEMENT TEI  ( teiHeader | text )*>

<!ELEMENT teiHeader  ( fileDesc )>

<!ELEMENT text  ( body )>

<!ELEMENT title   ( #PCDATA | abbr | add | c | cb | choice | corr | del | emph | fw | g | hi | l | layout | lb | name | note | num  | rhyme | s | sic | subst | vs  )*>
<!ATTLIST title
type CDATA #IMPLIED
>

<!ELEMENT titleStmt  ( title | author | respStmt )*>

<!-- <vs>, 'very special', used to mark a particularly exuberant, elaborate or unusually formed letter which is extended, generally into the upper or lower) margin. Values of 'rend' include 'arabesque', 'banderole', 'commas', 'flattened', 'point' and 'trumpet'. -->
<!ELEMENT vs  ( #PCDATA | c | abbr )*>
<!ATTLIST vs
rend CDATA #IMPLIED
>

=== UoEMainLibrary/pizan/html/xmlfinal/tabl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--?DOCTYPE TEI SYSTEM "http://www.tei-c.org/release/xml/tei/custom/schema/dtd/tei_all.dtd" -->
<!DOCTYPE TEI SYSTEM "halfway.dtd">
<!--?xml-stylesheet href="backrime.xsl" type="text/xsl"? -->
<?xml-stylesheet href="student.xsl" type="text/xsl"?>
<!--?xml-stylesheet href="newtestpropernames.xsl" type="text/xsl"? -->
<!--?xml-stylesheet href="diplo_forOCP.xsl" type="text/xsl"? -->
<!--?xml-stylesheet href="harley.xsl" type="text/xsl"? -->
<?xml-stylesheet type="text/css" href="classes.css"?>
<!--?xml-stylesheet type="text/css" href="test_oxy.css"? -->
<!--?xml-stylesheet href="harley.xsl" type="text/xsl"? -->
<TEI>
<teiHeader>
<fileDesc>
<titleStmt>
<title>London, British Library, Harley MS 4431</title>
<author>Christine de Pizan</author>
<respStmt>
<resp>Marked up by</resp><name>Team funded under AHRC award</name>
</respStmt></titleStmt>
<publicationStmt>
<authority>AHRC funded research project in Middle French 2004 to 2009 contact Charlie.Mansfield
at ed.ac.uk</authority>
<availability status="free"><p>http://www.pizan.lib.ed.ac.uk/</p></availability>
<date>2008</date>
</publicationStmt>
<sourceDesc>
<biblFull>
<titleStmt>
<title>The Queen's Manuscript</title>
<author>Christine de Pizan</author>
</titleStmt>
<publicationStmt>
<publisher>Manuscript</publisher>
<pubPlace>Paris</pubPlace>
<date>1414</date>
<idno type="url">http://www.bl.uk/catalogues/illuminatedmanuscripts</idno>
</publicationStmt></biblFull>
</sourceDesc></fileDesc>
</teiHeader>
<text>
<body>
<p>
<ref type="tablfm.htm"/>
<div1 n="Table des dictiez" type="Item">
<pb n="002" ed="v"/>
<cb n="c"/><!-- 38 lines -->
<lb n="TABL.002c:01"/><hi rend="cap3">C</hi>i commence <s>l</s>a ta<s>b</s><s>l</s>e des <g lemma="dicté" en="text, literary work" fr="texte, composition littéraire"><s>d</s>ictiez</g> en gene-
<lb n="TABL.002c:02"/>ral, balades, rondiaulx et autres par-
<lb n="TABL.002c:03"/>ticuliers livres qui sont contenus 
<lb n="TABL.002c:04"/>en ce present volume. LF 
<lb n="TABL.002c:05"/>¶ <s>P</s>remierement prologue adreçant LF 
<lb n="TABL.002c:06"/>à la <name ref="Isabeau"><c>R</c>oyne.</name> LF <hi rend="red">&#x95; I &#x95;</hi> LF
<lb n="TABL.002c:07"/>¶ Item cent balades. LF <hi rend="red">&#x95; ii &#x95;</hi>LF 
<lb n="TABL.002c:08"/>¶ Item virelaiz. LF <hi rend="red">&#x95; iii &#x95;</hi> LF 
<lb n="TABL.002c:09"/>¶ Item autres balades de <g lemma="plusieurs" en="many" fr="maint, nombreux">plusieurs</g> LF <hi rend="red">&#x95; iiii &#x95;</hi> LF <note>second dot written under the LF</note>
<lb n="TABL.002c:10"/>façons. LF 
<lb n="TABL.002c:11"/>¶ Item une assemblée de plusieurs LF <hi rend="red">v</hi> LF 
<lb n="TABL.002c:12"/><c>R</c>imes <g lemma="auques" en="almost" fr="presque">auques</g> toutes léonimes, en LF 
<lb n="TABL.002c:13"/>façon de lay, à qui vouldroit app<abbr type="re"/>ndre LF
<lb n="TABL.002c:14"/>à rimer léonimement. LF <hi rend="red">&#x95; v &#x95;</hi> LF <note>Item 5 is numbered twice, here and in line 11.</note>
<lb n="TABL.002c:15"/>¶ I<c>T</c>em ung autre lay. LF <hi rend="red">vi &#x95;</hi> LF
<lb n="TABL.002c:16"/>¶ I<c>T</c>em rondiaulx. LF <hi rend="red">vii</hi> LF 
<lb n="TABL.002c:17"/>¶ Item gieux à vendre. LF <hi rend="red">viii</hi> LF
<lb n="TABL.002c:18"/>¶ Item plusieurs autres balades. LF <hi rend="red">&#x95; ix</hi> LF 
<lb n="TABL.002c:19"/>¶ Item une complainte amoureuse. <hi rend="red">&#x95; x &#x95;</hi> LF 
<lb n="TABL.002c:20"/>¶ Item ancore autres balades. LF <hi rend="red">&#x95; xi &#x95;</hi> LF 
<lb n="TABL.002c:21"/>¶ Item l'epistre au <name ref="God+of+Love">dieu d'<c>a</c>mours</name>. LF <hi rend="red">xii</hi> LF 
<lb n="TABL.002c:22"/>¶ Item une autre complainte LF 
<lb n="TABL.002c:23"/>amoureuse. LF <hi rend="red">xiii</hi> LF
<lb n="TABL.002c:24"/>¶ Item le livre du debat de deux LF
<lb n="TABL.002c:25"/>amans. LF <hi rend="red">xiiii</hi> LF 
<lb n="TABL.002c:26"/>¶ Item le livre des iii &#x95; jugemens LF
<lb n="TABL.002c:27"/>qui s'adrece au <name ref="Jean+de+Werchin">Seneschal de <name ref="Hainaut"><c>h</c>aynau</name></name>. <hi rend="red">&#x95; xv</hi> LF
<lb n="TABL.002c:28"/>¶ Item le livre de <name ref="Poissy"><c>p</c>oissy</name> qui s'adresce LF 
<lb n="TABL.002c:29"/>à <name ref="Jean+de+Werchin ?">ung chevalier estrangier</name>. LF <hi rend="red">xvi</hi> LF
<lb n="TABL.002c:30"/>¶ Item le livre de l'epistre <name ref="Othéa">Othéa</name>. LF <hi rend="red">xvii</hi> LF 
<lb n="TABL.002c:31"/>¶ Item le livre du <name ref="Duke+of+True+Lovers">duc des vrays LF <hi rend="red">xviii</hi> LF 
<lb n="TABL.002c:32"/>amans</name>. LF 
<lb n="TABL.002c:33"/>¶ Item le chemin de lonc estude. LF <hi rend="red">xix</hi> LF 
<lb n="TABL.002c:34"/>¶ Item le livre de la <name ref="Marotelle">pastoure</name>. LF <hi rend="red">xx</hi> LF 
<lb n="TABL.002c:35"/>¶ Item les epistres contre le LF
<lb n="TABL.002c:36"/><name ref="Romance+of+the+Rose">Rommant de la <c>r</c>ose</name>. LF <hi rend="red">xxi</hi> LF 
<lb n="TABL.002c:37"/>¶ I<c>T</c>em une epistre que <name ref="Christine+de+Pizan"><abbr type="Crist"/>ine</name> LF 
<lb n="TABL.002c:38"/>envoya à <name ref="Eustache+Deschamps"><c>e</c>u<s>s</s>tace <c>m</c>orel</name> tout de LF <cb n="d"/><!-- 38 lines -->
<lb n="TABL.002d:01"/><c>R</c>imes equivoques. LF <hi rend="red">xxii</hi> LF
<lb n="TABL.002d:02"/>¶ Item une oroison de la vie et LF 
<lb n="TABL.002d:03"/>passion de <name ref="Jesus+Christ"><c>n</c><abbr type="ost"/>re <c>s</c>eigneur <c>j</c>h<abbr type="es"/>ucrist</name>. LF <hi rend="red">xxiii</hi> LF 
<lb n="TABL.002d:04"/>¶ Item proverbes moraulx. LF <hi rend="red">xxiiii</hi> LF 
<lb n="TABL.002d:05"/>¶ Item les enseignemens que LF 
<lb n="TABL.002d:06"/><name ref="Christine+de+Pizan"><abbr type="Crist"/>ine de <c>p</c>izan</name> donne à <name ref="Jean+du+Castel">son filz</name>. LF <hi rend="red">&#x95; xxv</hi> LF 
<lb n="TABL.002d:07"/>¶ Item une oroison de <name ref="Virgin+Mary"><c>n</c><abbr type="ost"/>re <c>d</c>ame</name>. LF <hi rend="red">xxvi</hi> LF
<lb n="TABL.002d:08"/>¶ Item les xv <note>'xv' is followed by a superscript half-moon; its sense is unclear.</note><c>J</c>oyes <name ref="Virgin+Mary"><c>n</c><abbr type="ost"/>re <c>d</c>ame</name>. LF <hi rend="red">xxvii</hi> LF
<lb n="TABL.002d:09"/>¶ Item le livre de <name ref="Prudence"><c>p</c>rudence</name> à LF 
<lb n="TABL.002d:10"/>l'enseignement de bien vivre. LF <hi rend="red">xxviii</hi> LF
<lb n="TABL.002d:11"/>¶ Item le livre de la cité des LF
<lb n="TABL.002d:12"/>dames. LF <hi rend="red">xxix</hi> LF
<lb n="TABL.002d:13"/>¶ I<c>T</c>em Cent balades de LF 
 <lb n="TABL.002d:14"/>dame et d'amant. LF <hi rend="red">xxx</hi> LF <note>The collection is entitled 'Cent balades d'amant et de dame on fol. 376a'.</note>
<!-- 24 blank line(s) here -->
<note>There is a short, sewn repair at the level of 002c, line 26</note>
</div1>
</p>
</body>
</text>
</TEI>

=== UoEMainLibrary/pizan/html/xmlfinal/tablfm.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--?DOCTYPE TEI SYSTEM "http://www.tei-c.org/release/xml/tei/custom/schema/dtd/tei_all.dtd" -->
<!DOCTYPE TEI SYSTEM "halfway.dtd">
<?xml-stylesheet href="fiche.xsl" type="text/xsl"?>
<TEI>
<teiHeader>
<fileDesc>
<titleStmt>
<title>London, British Library, Harley MS 4431</title>
<author>Christine de Pizan</author>
<respStmt>
<resp>Marked up by</resp><name>Team funded under AHRC award</name>
</respStmt></titleStmt>
<publicationStmt>
<authority>AHRC funded research project (2004-2009) centred on London, British Library, Harley MS 4431, the collection of her works prepared by Christine de Pizan and presented by her to Queen Isabeau of France early in 1414.  Contact Charlie.Mansfield@ ed.ac.uk</authority>
<availability status="free"><p>http://www.pizan.lib.ed.ac.uk/</p></availability>
<date>2008</date>
</publicationStmt>
<sourceDesc>
<biblFull>
<titleStmt>
<title>The Queen's Manuscript</title>
<author>Christine de Pizan</author>
</titleStmt>
<publicationStmt>
<publisher>Manuscript</publisher>
<pubPlace>Paris</pubPlace>
<date>1414</date>
<idno type="url">http://www.bl.uk/catalogues/illuminatedmanuscripts</idno>
</publicationStmt></biblFull>
</sourceDesc></fileDesc>
</teiHeader>
<text>
<body>
<p>
<div1 n="1" type="1">

<div9>
<div4><title type="main"><emph rend="headline">Table des dictiez</emph></title></div4>
<div4>The Table of Contents has no running-head and no rubric. It is introduced by a descriptive heading which is copied in brown ink, as are the titles of the thirty works contained in the Queen's Manuscript. The works are numbered separately, in red and in Roman. The numerals are centred in two rather irregular columns, set close to the right-hand margin of folios 002c and 002d. Here, as elsewhere in the manuscript, Roman numerals are generally preceded and followed by a punctus, a large dot, in red ink.</div4>
    <div4>After the works were numbered, champie line-fillers were inserted in the spaces left blank between the titles and the item numbers; in several cases these fillers obscure a punctus, traces of which can be seen underneath. The Table of Contents is the only item in MS 4431 which contains line-fillers of this type.</div4>

</div9>

</div1>
</p>
</body>
</text>
</TEI>

=== UoEMainLibrary/pizan/html/xmlfinal/cmp1fm.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--?DOCTYPE TEI SYSTEM "http://www.tei-c.org/release/xml/tei/custom/schema/dtd/tei_all.dtd" -->
<!DOCTYPE TEI SYSTEM "halfway.dtd">
<?xml-stylesheet href="fiche.xsl" type="text/xsl"?>
<?xml-stylesheet type="text/css" href="classes.css"?>
<TEI>
<teiHeader>
<fileDesc>
<titleStmt>
<title>London, British Library, Harley MS 4431</title>
<author>Christine de Pizan</author>
<respStmt>
<resp>Marked up by</resp><name>Team funded under AHRC award</name>
</respStmt></titleStmt>
<publicationStmt>
<authority>AHRC funded research project (2004-2009) centred on London, British Library, Harley MS 4431, the collection of her works prepared by Christine de Pizan and presented by her to Queen Isabeau of France early in 1414.  Contact Charlie.Mansfield@ ed.ac.uk</authority>
<availability status="free"><p>http://www.pizan.lib.ed.ac.uk/</p></availability>
<date>2008</date>
</publicationStmt>
<sourceDesc>
<biblFull>
<titleStmt>
<title>The Queen's Manuscript</title>
<author>Christine de Pizan</author>
</titleStmt>
<publicationStmt>
<publisher>Manuscript</publisher>
<pubPlace>Paris</pubPlace>
<date>1414</date>
<idno type="url">http://www.bl.uk/catalogues/illuminatedmanuscripts</idno>
</publicationStmt></biblFull>
</sourceDesc></fileDesc>
</teiHeader>
<text>
<body>
<p>
<div1 n="1" type="1">
<div9>
<div4><title type="main"><emph rend="headline">Une Autre Complainte Amoureuse</emph></title></div4>

<div4>The <emph rend="italic">Complainte</emph> is introduced by a miniature and a rubric. There is a complete set of running titles, save that the title on fol. 57r has been almost entirely cropped by the binder.</div4>

 <div4>The poem is made up of 15 seizains, rhyming <emph rend="italic">a10a10a10b4b10b10b10c4c10c10c10d4d10d10d10e4e10e10e10f4</emph> etc. The metrical structure is identical to that of the other two <emph rend="italic">Complaintes</emph> in the Queen's MS: Item 10 (<emph rend="italic">Une Complainte Amoureuse</emph>), and the conclusion of Item 18 (<emph rend="italic">Le Livre du Duc des Vrais Amans</emph>).</div4>

<div4>The opening line of Stanza 1 is set off by a champie initial and a border. The plan that each of the other stanzas should be introduced by a paragraph mark was not fully implemented. Only six were executed, before Stanzas 7 and 11-15; the marginal instructions left before Stanzas 2-6 and 8-10 were overlooked. This edition makes good these oversights and thus contains a complete set of paragraph marks.</div4>

<div4>There is no obvious reason for the one blank line, which is found halfway through Stanza 1.  With that exception, the stanzas are copied without a break. In this edition a blank line has been left after each stanza, mirroring the layout of the other two <emph rend="italic">Complaintes</emph>.</div4>

</div9>
</div1>
</p>
</body>
</text>
</TEI>
